// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.ges.domain;

import com.ges.domain.Mark;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Mark_Roo_Configurable {
    
    declare @type: Mark: @Configurable;
    
}
