// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.ges.domain;

import com.ges.domain.Profile;

privileged aspect Profile_Roo_JavaBean {
    
    public String Profile.getProfile() {
        return this.profile;
    }
    
    public void Profile.setProfile(String profile) {
        this.profile = profile;
    }
    
}
