// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.ges.domain;

import com.ges.domain.Subject;

privileged aspect Subject_Roo_JavaBean {
    
    public String Subject.getTitle() {
        return this.title;
    }
    
    public void Subject.setTitle(String title) {
        this.title = title;
    }
    
}
